name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - name: Build xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build caddy-trojan
        run: xcaddy build --with github.com/imgk/caddy-trojan
      - name: Show info
        run: |
          pwd
          ls -al

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: caddy

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT }}
          file: caddy
          tag: ${{ github.ref }}
          overwrite: true
